name: 'BoltCI Action'
description: 'The action used to run the BoltCI test runner.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Call out to docker image
      uses: "docker://ghcr.io/boltci/boltci:0.0.7"
      with:
        args: "Matt"
