name: 'BoltCI Action'
description: 'The action used to run the BoltCI test runner.'
inputs:
  index: 
    description: 'Index of the chunk to run'
    required: true
  chunks: 
    description: 'Number of chunks'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-boltci-latest
    - name: Call out to docker image
      uses: "docker://ghcr.io/boltci/boltci:latest"
      with:
        args: "${{ inputs.chunks }} ${{ inputs.index }}"
